### PR TITLE
remove to call C functions and use C++ std::fstream

### PR DESCRIPTION
**Pull request by sizeofvoid**
- Point std{in,out,err} descriptors to /dev/null (C++ wey)

### CODE REVIEW

**Comment by orignal** [comment]
I'm not sure we can redefine descriptors 0,1,2 this way.

**Comment by orignal** [comment]
It doesn't do what it's supposed to. We must make sure that these file descriptors are redirected properly rather than streams to make sure they are not taken for sockets, etc.

**Comment by sizeofvoid** [comment]
i2pd-2.10.0/DaemonLinux.cpp:79:24: error: expression is not assignable
                stdin  = freopen("/dev/null", "r", stdin);
                ~~~~~  ^
i2pd-2.10.0/DaemonLinux.cpp:80:12: error: expression is not assignable
                                stdout = freopen("/dev/null", "w", stdout);
                                ~~~~~~ ^
i2pd-2.10.0/DaemonLinux.cpp:81:12: error: expression is not assignable
                                stderr = freopen("/dev/null", "w", stderr);

clang -v
clang version 3.9.0 (tags/RELEASE_390/final)
Target: amd64-unknown-openbsd6.0
Thread model: posix

**Comment by orignal** [comment]
Target: amd64-unknown-**openbsd**6.0
Add #if  !defined(OPENSBD) or something like this

**Comment by sizeofvoid** [comment]
Is this ´#define´ to support OpenBSD as target system acceptable as pull request?

**Comment by orignal** [comment]
Sure it is

**Pull request closed without merging**
