### PR TITLE
the binary should be i2pd

### PR DESCRIPTION
**Pull request by guanqun**
Shouldn't the name be `i2pd`? :)

### CODE REVIEW

**Comment by orignal** [comment]
Now now, should be discussed with kytv first.

**Comment by guanqun** [comment]
I'm using `cmake` to compile and the generated binary name is `i2pd`, isn't it?

**Comment by orignal** [comment]
Probably, but plain Makefile still generates i2p

**Comment by kytvi2p** [comment]
It's fine with me. ;)

**Comment by guanqun** [comment]
I can change the plain Makefile so that it generates `i2pd`, how do you think?

**Comment by orignal** [comment]
Again, it must be discused with kytv about his packaging

**Comment by meeh420** [comment]
Kytv said it was fine.

**Pull request merged**
