### PR TITLE
Testing auto-build

### PR DESCRIPTION
**Pull request by manasb**
Test

### CODE REVIEW

**Comment by manasb** [comment]
Sorry, still learning my way around GitHub.

**Comment by mlt** [comment]
@manasb You can create a feature branch that you can rebase on top of current openssl and then force push it into your repo. This way you can keep clean Pull Request without the need to close/reopen or merging upstream openssl back into your branch.

**Comment by manasb** [comment]
Cool! Thanks.

**Comment by mlt** [comment]
In fact you might get by resurrecting this PR with whatever changes you had in mind. To do this, "rename" *openssl* into *upstream* with `git fetch origin openssl:upstream` and then while you are on your entangled *openssl*, rebase it on top of *upstream* with `git rebase -i upstream`. You might need to resolve a few potential issues on the way, but you should end up with clean change set on top of upstream without any merges in the way. Then force push **your** _openssl_ into **your** repo. GitHub should be smart enough to show only pending commits in this PR. Have fun rebasing!

**Pull request closed without merging**
