### PR TITLE
Build DEB package with CMake and uPNP

### PR DESCRIPTION
**Pull request by v2e**
- Build Debian package using CMake instead of the shipped Makefile
- enable uPNP support during build

### CODE REVIEW

**Comment by orignal** [comment]
We don't enable UPnP intentionally

**Comment by v2e** [comment]
> We don't enable UPnP intentionally
Why? I tested on a couple of my PCs, and with UPNP it works much more effective (more transit traffic).

And what about the CMake build itself? It is independent of UPNP.

**Comment by r4sas** [comment]
About cmake:
If you will give to me 10 reasons to build deb packages with cmake, I'll think about this

**Comment by orignal** [comment]
UPnP requires extra dependancy, and most of Linux users don't want it, because they know how to forward ports manually

**Comment by majestrate** [comment]
from what I understand the cmake build files aren't really used much

**Comment by orignal** [comment]
FreeBSD build uses it

**Comment by v2e** [comment]
@r4sas This repository contains the CMake files already. So I just suggested to use them during the DEB package build. It was nothing more but a suggestion. So it is perfectly OK to decline it. And sure enough I am not going to "give to you 10 reasons".

@orignal You may be right about the linux users knowing how to forward ports by hand. Still, I was considering the following:

1. Most torrent-clients (as well as some other software) use UPNP anyway, so the library may be there on the user's PC anyway. And this library is a standard one from the Debian repository.
2. The I2P documentation seems to recommend the user NOT to use the same port all the time. If I am not mistaken, it is recommended to use a random port. In such case it would be not too convenient to forward a new port each time by hand.

This being said, I'd like to emphasize that by no means I insist on these commits. I will use them on my own system, but it is totally up to you to decide what is going to enter the code tree. And thank you guys for working on I2PD! Please continue. :)

**Comment by r4sas** [comment]
@v2e, =)

**Pull request closed without merging**
