### PR TITLE
Rewrite Dockerfile to use multi-stage docker build

### PR DESCRIPTION
**Pull request by Nyoroon**

### CODE REVIEW

**Comment by l-n-s** [comment]
@Nyoroon thank you for your contribution. Dockerfile in the root is managed by @mikalv, I'm not sure if he approves those changes. There is [alternative docker file in our project](https://github.com/PurpleI2P/i2pd/tree/openssl/contrib/docker), which has some more improvements -- we can accept your changes there.

Can you briefly explain what multi-stage build is, and why do we need it?

**Comment by Nyoroon** [comment]
Docker multi-stage build allows us to create "temporary" images to build application and copy files from it to build image that user will run.

This is mainly to simplify Dockerfile and increase readability -- with it we don't need to delete *-dev packages and run build in one command to keep image size small. Also we can remove git clone and take code from current dir, which is more flexible.

**Comment by majestrate** [comment]
This new dockerfile looks a lot more consice and clean.

**Comment by l-n-s** [comment]
I've tried to apply your changes to `contrib/docker/Dockerfile` and there are 2 problems with it:

1) Minimum docker version is bumped to 17.05, so on ubuntu LTS I had to install docker from upstream repo. Not a big problem, just to note.
2) Dockerhub can't build automatically from repo now. I think it is related to the "build context" (it needs to copy source code, but the building context is `contrib/docker`). Needs some workaround.

```
 Step 3/21 : WORKDIR /src ---> 9f8247390497 Removing intermediate container 0a43998eb8c3 
 Step 4/21 : COPY . /src ---> 32296292085f Removing intermediate container 46c5554951c5 
 Step 5/21 : RUN make -j$(nproc) ---> Running in c80f27cebe7b 
[91mmake: *** No targets specified and no makefile found. Stop.
 [0m 
Removing intermediate container c80f27cebe7b 
The command '/bin/sh -c make -j$(nproc)' returned a non-zero code: 2
```

**Comment by Nyoroon** [comment]
@l-n-s to utilize COPY directive "build context" should be at repo root and path to Dockerfile `contrib/docker/Dockerfile`, otherwise we should copy sources to `contrib/docker/` or use git. I'll rewrite `contrib/docker/Dockerfile` next week.

**Comment by majestrate** [comment]
since the old dockerfile was removed should we merge this one once the conflicts are resolved?

**Comment by l-n-s** [comment]
@majestrate automated Dockerhub builds don't work, so we can't merge it currently

**Comment by Nyoroon** [comment]
I've rebased and build succeeded: https://hub.docker.com/r/nyoroon/i2pd/builds/bqbgr7cvqkcctatgkcxykdx/

**Pull request closed without merging**
