### PR TITLE
Add implementation of tests with CMake, plus a few minor fixes

### PR DESCRIPTION
**Pull request by barracuda156**
@r4sas @orignal The issue re broken atomics when using GCC builtin is specific to Darwin PPC, not any PPC (size of bool is defined by ABI, not by arch). Therefore, let’s use the flag only where it is actually needed (until a fix to Boost is backported from develop to versions currently in use).

Tests build fine now.

On 10.6 PPC all tests pass but one, `test-blinding`. It fails with SIGTRAP, apparently being unable to dynamically link `__ZN3i2p6config9m_OptionsE` symbol. Not sure why – any suggestions are welcome.

### CODE REVIEW

**Comment by barracuda156** [comment]
Tests on macOS PPC:
```
--->  Testing i2pd
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_i2pd/i2pd/work/build" && ctest test 
Test project /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_i2pd/i2pd/work/build
      Start  1: test-http-merge_chunked
 1/12 Test  #1: test-http-merge_chunked ..........   Passed    0.01 sec
      Start  2: test-http-req
 2/12 Test  #2: test-http-req ....................   Passed    0.01 sec
      Start  3: test-http-res
 3/12 Test  #3: test-http-res ....................   Passed    0.01 sec
      Start  4: test-http-url_decode
 4/12 Test  #4: test-http-url_decode .............   Passed    0.01 sec
      Start  5: test-http-url
 5/12 Test  #5: test-http-url ....................   Passed    0.01 sec
      Start  6: test-base-64
 6/12 Test  #6: test-base-64 .....................   Passed    0.01 sec
      Start  7: test-gost
 7/12 Test  #7: test-gost ........................   Passed    0.01 sec
      Start  8: test-gost-sig
 8/12 Test  #8: test-gost-sig ....................   Passed    0.07 sec
      Start  9: test-x25519
 9/12 Test  #9: test-x25519 ......................   Passed    0.02 sec
      Start 10: test-aeadchacha20poly1305
10/12 Test #10: test-aeadchacha20poly1305 ........   Passed    0.03 sec
      Start 11: test-elligator
11/12 Test #11: test-elligator ...................   Passed    0.02 sec
      Start 12: test-blinding
12/12 Test #12: test-blinding ....................SIGTRAP***Exception:   3.82 sec

92% tests passed, 1 tests failed out of 12

Total Test time (real) =   4.04 sec

The following tests FAILED:
	 12 - test-blinding (SIGTRAP)
Errors while running CTest
```
Failing test in GDB:
```
(gdb) run
Starting program: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_i2pd/i2pd/work/build/tests/test-blinding 
Reading symbols for shared libraries +++++++++++++... done
dyld: Symbol not found: __ZN3i2p6config9m_OptionsE
  Referenced from: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_i2pd/i2pd/work/build/tests/test-blinding
  Expected in: dynamic lookup

Program received signal SIGTRAP, Trace/breakpoint trap.
0x8fe01078 in __dyld_dyld_fatal_error ()
(gdb) where
#0  0x8fe01078 in __dyld_dyld_fatal_error ()
#1  0x8fe086e0 in __dyld__ZN4dyld5_mainEPK11mach_headermiPPKcS5_S5_ ()
#2  0x8fe017cc in __dyld__ZN13dyldbootstrap5startEPK11mach_headeriPPKcl ()
#3  0x8fe01064 in __dyld__dyld_start ()
```

**Comment by orignal** [comment]
Please take https://github.com/PurpleI2P/i2pd/commit/b4c226f4b35bd36d2f26744333778cfc2d851cd1 and try blinding test again

**Comment by barracuda156** [comment]
> Please take [b4c226f](https://github.com/PurpleI2P/i2pd/commit/b4c226f4b35bd36d2f26744333778cfc2d851cd1) and try blinding test again

Thank you, I will try and update soon.

**Comment by barracuda156** [comment]
> Please take [b4c226f](https://github.com/PurpleI2P/i2pd/commit/b4c226f4b35bd36d2f26744333778cfc2d851cd1) and try blinding test again

@orignal Looks like same story:
```
--->  Testing i2pd
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_i2pd/i2pd/work/build" && ctest test 
Test project /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_i2pd/i2pd/work/build
      Start  1: test-http-merge_chunked
 1/12 Test  #1: test-http-merge_chunked ..........   Passed    0.04 sec
      Start  2: test-http-req
 2/12 Test  #2: test-http-req ....................   Passed    0.04 sec
      Start  3: test-http-res
 3/12 Test  #3: test-http-res ....................   Passed    0.04 sec
      Start  4: test-http-url_decode
 4/12 Test  #4: test-http-url_decode .............   Passed    0.04 sec
      Start  5: test-http-url
 5/12 Test  #5: test-http-url ....................   Passed    0.04 sec
      Start  6: test-base-64
 6/12 Test  #6: test-base-64 .....................   Passed    0.03 sec
      Start  7: test-gost
 7/12 Test  #7: test-gost ........................   Passed    0.03 sec
      Start  8: test-gost-sig
 8/12 Test  #8: test-gost-sig ....................   Passed    0.27 sec
      Start  9: test-x25519
 9/12 Test  #9: test-x25519 ......................   Passed    0.05 sec
      Start 10: test-aeadchacha20poly1305
10/12 Test #10: test-aeadchacha20poly1305 ........   Passed    0.10 sec
      Start 11: test-blinding
11/12 Test #11: test-blinding ....................SIGTRAP***Exception:   0.12 sec
      Start 12: test-elligator
12/12 Test #12: test-elligator ...................   Passed    0.07 sec

92% tests passed, 1 tests failed out of 12

Total Test time (real) =   0.95 sec

The following tests FAILED:
	 11 - test-blinding (SIGTRAP)
Errors while running CTest
```

This is on 10.6.8 in Rosetta, I can verify on PPC natively a bit later, but pretty sure it gonna be the same.

**Comment by orignal** [comment]
Can you run test-blinding under a debugger to see what line causes this crash? Because even valgrind shows nothing on Linux.

**Comment by barracuda156** [comment]
> Can you run test-blinding under a debugger to see what line causes this crash? Because even valgrind shows nothing on Linux.

Sure, will build on PPC natively now and try with GDB.

**Comment by barracuda156** [comment]
@orignal Native ppc32 build (a bit slower, since on 2.3DC with less RAM):
```
--->  Testing i2pd
Executing:  cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_i2pd/i2pd/work/build" && ctest test 
Test project /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_i2pd/i2pd/work/build
      Start  1: test-http-merge_chunked
 1/12 Test  #1: test-http-merge_chunked ..........   Passed    0.07 sec
      Start  2: test-http-req
 2/12 Test  #2: test-http-req ....................   Passed    0.11 sec
      Start  3: test-http-res
 3/12 Test  #3: test-http-res ....................   Passed    0.16 sec
      Start  4: test-http-url_decode
 4/12 Test  #4: test-http-url_decode .............   Passed    0.09 sec
      Start  5: test-http-url
 5/12 Test  #5: test-http-url ....................   Passed    0.10 sec
      Start  6: test-base-64
 6/12 Test  #6: test-base-64 .....................   Passed    0.05 sec
      Start  7: test-gost
 7/12 Test  #7: test-gost ........................   Passed    0.10 sec
      Start  8: test-gost-sig
 8/12 Test  #8: test-gost-sig ....................   Passed    0.28 sec
      Start  9: test-x25519
 9/12 Test  #9: test-x25519 ......................   Passed    0.05 sec
      Start 10: test-aeadchacha20poly1305
10/12 Test #10: test-aeadchacha20poly1305 ........   Passed    0.07 sec
      Start 11: test-blinding
11/12 Test #11: test-blinding ....................SIGTRAP***Exception:   8.89 sec
      Start 12: test-elligator
12/12 Test #12: test-elligator ...................   Passed    0.15 sec

92% tests passed, 1 tests failed out of 12

Total Test time (real) =  10.28 sec

The following tests FAILED:
	 11 - test-blinding (SIGTRAP)
```
GDB run:
```
(gdb) run
Starting program: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_i2pd/i2pd/work/build/tests/test-blinding 
Reading symbols for shared libraries +++++++++++++... done
dyld: Symbol not found: __ZN3i2p6config9m_OptionsE
  Referenced from: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_security_i2pd/i2pd/work/build/tests/test-blinding
  Expected in: dynamic lookup


Program received signal SIGTRAP, Trace/breakpoint trap.
0x8fe01078 in __dyld_dyld_fatal_error ()
(gdb) where
#0  0x8fe01078 in __dyld_dyld_fatal_error ()
#1  0x8fe086e0 in __dyld__ZN4dyld5_mainEPK11mach_headermiPPKcS5_S5_ ()
#2  0x8fe017cc in __dyld__ZN13dyldbootstrap5startEPK11mach_headeriPPKcl ()
#3  0x8fe01064 in __dyld__dyld_start ()
```
Test code used:
```
#include <cassert>
#include <memory>
#include <string.h>
#include "Blinding.h"
#include "Identity.h"
#include "Timestamp.h"

using namespace i2p::data;
using namespace i2p::util;
using namespace i2p::crypto;

void BlindTest (SigningKeyType sigType)
{
	auto keys = PrivateKeys::CreateRandomKeys (sigType);
	BlindedPublicKey blindedKey (keys.GetPublic ());
	auto timestamp = GetSecondsSinceEpoch ();	
	char date[9];
	GetDateString (timestamp, date);
	uint8_t blindedPriv[32], blindedPub[32]; 
	auto publicKeyLen = blindedKey.BlindPrivateKey (keys.GetSigningPrivateKey (), date, blindedPriv, blindedPub);
	uint8_t blindedPub1[32];	
	blindedKey.GetBlindedKey (date, blindedPub1);
	// check if public key produced from private blinded key matches blided public key
	assert (!memcmp (blindedPub, blindedPub1, publicKeyLen));
	// try to sign and verify
	std::unique_ptr<Signer> blindedSigner (PrivateKeys::CreateSigner (blindedKey.GetBlindedSigType (), blindedPriv));
	uint8_t buf[100], signature[64];
	memset (buf, 1, 100);
	blindedSigner->Sign (buf, 100, signature);	
	std::unique_ptr<Verifier> blindedVerifier (IdentityEx::CreateVerifier (blindedKey.GetBlindedSigType ()));
	blindedVerifier->SetPublicKey (blindedPub);
	assert (blindedVerifier->Verify (buf, 100, signature));		
}

int main ()
{
	// EdDSA test	
	BlindTest (SIGNING_KEY_TYPE_EDDSA_SHA512_ED25519);
	// RedDSA test	
	BlindTest (SIGNING_KEY_TYPE_REDDSA_SHA512_ED25519);
}
```
P. S. For a notice, I added patches on top of 2.44.0. If some other changes are needed aside of https://github.com/PurpleI2P/i2pd/commit/b4c226f4b35bd36d2f26744333778cfc2d851cd1 and my CMake implementation fixes, those are not made.

**Comment by orignal** [comment]
You should build with debug

**Comment by barracuda156** [comment]
> You should build with debug

Ok, will do in a couple of days and update you.

**Comment by r4sas** [comment]
I'm pulling this PR, even if problem on PPC is still not resolved.

**Comment by barracuda156** [comment]
> I'm pulling this PR, even if problem on PPC is still not resolved. Thank you!

@r4sas Thank you, sure!

Sorry for an interruption, I am away from PPC machines until later this month. Did not find time to sort debugging before leaving :(
Will be done in a while, I did not forget.

**Pull request merged**
