### PR TITLE
Fucking monero.

### PR DESCRIPTION
**Pull request by StPrimateCoder**
Fucking the "Monero" organisation simply stealing your a code. 
I think it better option for problem. Because "Monero" can use other name I wrote 'or similar projects' . I did this. Now you must accept or refuse about my idea. You may think about my idea 20 years and more.

Do good.

### CODE REVIEW

**Comment by majestrate** [comment]
would prefer to not perpetuate e-drama.

**Comment by orignal** [comment]
@majestrate although this PR definitly will not be accepted, however he has a point. We might formulate the same more politely, like our code can't be used in any project under Monero's license

**Comment by majestrate** [comment]
You could always do GPL-3 but that would put i2pd at a massive disadvantage.

**Comment by v2e** [comment]
@majestrate What kind of disadvantage?

**Pull request closed without merging**
