### PR TITLE
memory leak and concurrency fixes

### PR DESCRIPTION
**Pull request by simonvetter**
This fixes a few memory leaks (destructors not being virtual) and concurrency issues (missing locks) in Tunnel, TunnelPool and TunnelConfig classes.

### CODE REVIEW

**Comment by orignal** [comment]
Will slow down everything. Most of code is called from the single  tunnels thread.

**Comment by simonvetter** [comment]
Reworked the code, added extra locks.

I haven't seen much of a slowdown in my tests but admittedly I've only been testing for a few hours.
At any rate, it fixes a lot of races reported by the thread sanitizer and a bunch of memory corruption issues. If the thread sanitizer is to be trusted, this code is definitely called from multiple concurrent threads.

**Comment by r4sas** [comment]
That PR brokes usage on Windows.

**Comment by simonvetter** [comment]
Would you have any logfile, core dump or pointer so I can debug that windows deadlock? I'd like to fix it and re-submit the PR if possible.
Unfortunately I don't have any windows system around to test.

**Comment by simonvetter** [comment]
By the way, if you'd rather fix races and memory issues yourself, I can post the threadsan/asan logs in here. Let me know.

**Comment by r4sas** [comment]
> Would you have any logfile, core dump or pointer so I can debug that windows deadlock? I'd like to fix it and re-submit the PR if possible. Unfortunately I don't have any windows system around to test.

It's really hard to debug such things on windows because we are using MinGW g++ and here no such debuggers like in MSVS. On start no dumps created inside gdb and no log lines about errors in execution inside tunnels thread.

I'll try to add print to logs in places where you made changes, but it will be later (lack of time).

**Pull request merged**
