### PR TITLE
BOB modifications.

### PR DESCRIPTION
**Pull request by rszibele**
Hi, I've fixed/added/changed the following:

1. BOBCommandSession: added telnet support (https://github.com/PurpleI2P/i2pd/issues/1351) and removed C string pointer arithmetic.
2. Cleaned up the status command.
3. Added the other outputs to the `list` command (https://github.com/PurpleI2P/i2pd/issues/1352#issuecomment-494902499) and it now uses the same string building function like the status command.
4. Added extra validation to the `start` command. It prevents a segfault (https://github.com/PurpleI2P/i2pd/issues/1355) and also prevents some inconsistent states.
5. Added the `help` command.
6. Separated the address into outhost and inhost (will be required for resolving).

**Future TODO:**
If this patch is accepted and I have some time I might implement host resolving if you want to add it (https://github.com/PurpleI2P/i2pd/issues/1357). Java BOB supports arbitrary hostnames, e.g. you can create an outbound tunnel to google.com.

Is there an IRC channel or mailing list for i2pd?

### CODE REVIEW

**Comment by K1773R** [comment]
@rszibele there is #i2pd-dev on irc2p.

**Comment by orignal** [comment]
People complain, one of these changes has broken transmission-i2p. Must be investigated.

**Comment by rszibele** [comment]
I will look into it. Is there a specific error message?

**Comment by orignal** [comment]
I asked for the details. But I guess it's easier to just run transmission and try..

**Pull request merged**
