### PR TITLE
Fix compilation without deprecated OpenSSL APIs

### PR DESCRIPTION
**Pull request by neheb**
More info: https://github.com/openwrt/packages/pull/7845

### CODE REVIEW

**Comment by orignal** [comment]
what is this change for? 
you don't need to check LEGACY_OPENSSL and CHAHA20 together, because LEGACY_OPENSSL means openssl below 1.1.0

**Comment by neheb** [comment]
Yes? In OpenSSL 1.1, chacha and poly1305 can be compile time disabled.

**Comment by neheb** [comment]
Space. OpenWrt is an embedded distro.

**Comment by orignal** [comment]
Please elaborate. Do you believe own implementation of chacha20/poly1305 produces smaller binary vs. if we call it from openssl in case of 1.1?

**Comment by neheb** [comment]
1.1

no-chacha no-poly1305 can be passed to OpenSSL's Makefile to disable it at compile time. Meaning, those functions are completely unavailable in libssl (or libcrypto) and cannot be used.

This pull request is only a fix for compilation.

**Comment by orignal** [comment]
They are disable automatically because LEGACY_OPENSSL is false in case of 1.1 and up, so this code never gets compiled.
https://github.com/PurpleI2P/i2pd/blob/openssl/libi2pd/Crypto.h#L24
Seems you PR does nothing but adds more code

**Comment by neheb** [comment]
...................................

Do I need to send you logs or something? This is definitely failing when chacha20 or poly1305 are disabled at the openssl level. This has nothing to do with the version of openssl.

**Comment by neheb** [comment]
Oh actually here: https://gist.github.com/neheb/81e1d7c55fd8d3c5556892999e393b50

**Comment by orignal** [comment]
What version of openssl do you build with? 1.1.0?

**Comment by neheb** [comment]
1.1.1. 1.1.0 should give identical results.

**Comment by orignal** [comment]
If I understood you right, openssl 1.1 for openwrt doesn't contain AEAD/Chacha20/Poly1305.
Let's wait for @LLE8

**Comment by neheb** [comment]
By default it does. However it can be disabled through "make menuconfig"

**Comment by orignal** [comment]
I have added chacha20/poly1305 check. 
https://github.com/PurpleI2P/i2pd/commit/f74b27c58c9416083bcab5c7a8c0ff2f4bc57586
Please verify on openwrt, fix the rest and create new PR

**Pull request closed without merging**
