### PR TITLE
CPU: remove AVX code, switch to __builtin for AES detection

### PR DESCRIPTION
**Pull request by r4sas**
Removing outdated AVX support checks, one and only AVX asm block and switching to __builtin_cpu_supports to detect AES support.

### CODE REVIEW

**Comment by r4sas** [comment]
@khumarahn @yhaenggi @barracuda156
Can you check changes on your systems and platforms?

**Comment by barracuda156** [comment]
@r4sas If we are to believe GCC documentation, these builtins are Intel-only: https://gcc.gnu.org/onlinedocs/gcc/x86-Built-in-Functions.html
So I would expect this to fail. However I will check to make sure and update you.

**Comment by r4sas** [comment]
Yes, I know that it is x86-only, but, as you can see, some architectures supports them too.
Anyway, I think it is better to limit checks to supported-only archs. I'll push some more changes now.

**Comment by barracuda156** [comment]
@pkubaj If you got a minute, could you please comment on whether this works on the new POWER systems?

**Comment by barracuda156** [comment]
From 7a8aa37eb2c45a96ced900d11103cfa0624cee24 it builds fine for me.

**Pull request merged**
