### PR TITLE
added spec and service files

### PR DESCRIPTION
**Pull request by BOPOHA**
There are all you need to build RPMs in COPR repo.
For example https://copr.fedorainfracloud.org/coprs/vorona/i2pd/

### CODE REVIEW

**Comment by l-n-s** [comment]
So, it is like PPA in Ubuntu, but for Fedora? Are those files required to be in our root directory, or may be we can find some better directory for it?

**Comment by BOPOHA** [comment]
> So, it is like PPA in Ubuntu, but for Fedora?

Yes, it works for all redhat-based systems.
( as another way, you can build Ubuntu, Debian, Centos, etc-etc-etc, in one place, here https://build.opensuse.org/)

> or may be we can find some better directory for it?

well, If it is really necessary, i think we can. Just move it and l'll fix paths.

**Comment by l-n-s** [comment]
Cool. I guess `contrib/rpm` directory is the best place for such files.

**Comment by orignal** [comment]
@l-n-s yes, please move it there

**Comment by l-n-s** [comment]
done

**Pull request merged**
