### PR TITLE
Update HTTPProxy.cpp

### PR DESCRIPTION
**Pull request by jiigen**
Remove DoNotTrack flag from HTTP Request header.

### CODE REVIEW

**Comment by r4sas** [comment]
Why remove this line? This flag makes no sense.

**Comment by jiigen** [comment]
> Why remove this line? This flag makes no sense.

Yes...it's useless so why keep it?

**Comment by r4sas** [comment]
Because in case of leaving it in requests it can be used for fingerprinting (two possible values with and w/o flag).

**Comment by jiigen** [comment]
Exactly, maybe there's a misunderstanding. I've added that line not removed it. The flag DNT is actually not removed by i2pd http proxy.

**Comment by r4sas** [comment]
Sorry, overworked at work :)

In this case, we must make sure to add the same in Java I2P so that clients do not differ for services.

**Comment by jiigen** [comment]
> Sorry, overworked at work :)
> 
> In this case, we must make sure to add the same in Java I2P so that clients do not differ for services.

I agree but currently they already differ in the HTTP Headers anyway. Java I2P doesn't remove Accept* while i2pd removes them all and only keeps "Accept-Encoding" (which is better IMHO)

**Pull request merged**
