### PR TITLE
[cmake] remove windows build support

### PR DESCRIPTION
**Pull request by r4sas**
@LLE8, @khumarahn, @AMDmi3, @ffontaine, @radfish, @yangfl
Please check it that change will not broke building in your build systems.

### CODE REVIEW

**Comment by AMDmi3** [comment]
It breaks the build
```===>  Performing in-source build
/bin/mkdir -p /wrkdirs/usr/ports/security/i2pd/work/i2pd-9a09050
-- The C compiler identification is Clang 8.0.1
-- The CXX compiler identification is Clang 8.0.1
-- Check for working C compiler: /usr/local/libexec/ccache/cc
-- Check for working C compiler: /usr/local/libexec/ccache/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/libexec/ccache/c++
-- Check for working CXX compiler: /usr/local/libexec/ccache/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:10 (if):
  if given arguments:

    "WIN32" "or" "MSVC" "or" "MSYS" "or" "MINGW"

  Unknown arguments specified


-- Configuring incomplete, errors occurred!


```

**Comment by khumarahn** [comment]
Same in gentoo.

**Comment by r4sas** [comment]
Can it be that this "or" is case-sensetive and required to be written in uppercase?

**Comment by AMDmi3** [comment]
> Will replace for test.

This now builds fine on FreeBSD.

**Comment by khumarahn** [comment]
It worked on gentoo (arm), but the rest of the package is still compiling because my arm machine is very slow.

**Comment by LLE8** [comment]
I usually use debuild, not cmake.

**Comment by r4sas** [comment]
> I usually use debuild, not cmake.

I'm about openwrt.

**Comment by LLE8** [comment]
I don't use cmake in OpenWrt, make only.

**Comment by ffontaine** [comment]
It builds fine on buildroot

**Comment by r4sas** [comment]
Ok, I think in this case other systems will build without issues. Thanks everyone.

**Pull request merged**
