### PR TITLE
fixed HTTP connection being reset on Windows

### PR DESCRIPTION
**Pull request by ygrishin**
Ok, so... Some fix has been found. Please note that this is rather a "quick and dirty fix" as I haven't gained full understanding of the server yet. Should you be not satisfied with the quality of patch proposed, feel free to decline. Having that kind of scenario we can postpone it until I understand ins and outs of the server, estimate for that is 2 to 4 weeks.

Nevertheless, it looks like it's a variant of Kohloff's type 3 server with a thread pool (pool size for the time being is 1). I've spotted a couple of issues (memory leak, dead code etc) and will be actively creating new Github issues soon. You may rest assured that this does patch does not break Linux branch, has been tested just now.

### CODE REVIEW

**Comment by orignal** [comment]
Why would your change fix connection reset since everything is running inside single thread?

**Comment by ygrishin** [comment]
I don't think having a single thread imply that connection cannot be reset. Was it a copy of Kohloff's server initially?

**Comment by orignal** [comment]
No.
Please tell me, does it fix the problem or not?

**Comment by ygrishin** [comment]
Yes it does. Tested for Windows and Linux.

**Pull request merged**
